### ISSUE TITLE
额外的输出

### ISSUE THREAD

**Issue by AnzhiZhang** [DeeChael/Kaiheila.java#3]
此处有调试用输出，建议删除或改为 logger.debug
https://github.com/DeeChael/Kaiheila.java/blob/0a0d3162918925f9d2e7932d7fdb015a68187cdb/src/main/java/net/deechael/khl/message/cardmessage/CardMessage.java#L22

**Comment by DeeChael** [comment]
这项目都弃坑了怎么还有人用
建议使用JKook：https://github.com/SNWCreations/JKook
