### ISSUE TITLE
应当给卡片消息相关 api： Section、Module、Element等的 setter 函数加上 return this

### ISSUE THREAD

**Issue by AnzhiZhang** [DeeChael/Kaiheila.java#5]
以便链式操作调用，否则将会出现如下的屎山情况：
![image](https://user-images.githubusercontent.com/37402126/207998212-edb833b6-3280-4cc8-b3a5-cd482161178c.png)

另外建议也提供带参数的 Constructor

**Comment by DeeChael** [comment]
这项目都弃坑了怎么还有人用
建议使用JKook：https://github.com/SNWCreations/JKook
